# By using the >> operator followed by the file name, the response will be saved to the file.
# If the file already exists, a warning will be displayed, and the file won't be overwritten.
# To overwrite the file, use the >>! operator.


# Don't overwrite the file
POST https://httpbin.org/post HTTP/1.1
Accept: application/json
Content-Type: application/json

{
  "name": "Kulala"
}

>> kulala.json

###

# Overwrite the file
POST https://httpbin.org/post HTTP/1.1
Accept: application/json
Content-Type: application/json

{
  "name": "Kulala"
}

>>! kulala.json

