gui:
  language: 'en'
  expandFocusedSidePanel: true
  showListFooter: false # for seeing the '6 of 20' message in list panels
  showBranchCommitHash: true # show commit hashes alongside branch names
  showBottomLine: false # for hiding the bottom information line (unless it has important information to tell you)
  showCommandLog: false
  nerdFontsVersion: "3" # nerd fonts version to use ("2" or "3"); empty means don't show nerd font icons
git:
  log:
    showWholeGraph: true
  disableForcePushing: true
