return {
  'user.mvn-build',
  'user.mvn-build-skip-tests',
  'user.mvn-application-tests',
  'user.mvn-docker-tests',
  'user.mvn-component-tests',
  'user.mvn-api-tests',
  'user.mvn-active-profiles',
  'user.mvn-all-profiles',
  'user.docker-compose-up',
  'user.docker-compose-kill',
  'user.docker-compose-stop',
  'user.gradle-build',
  'user.gradle-test',
  'user.gradle-tasks',
  'user.gradle-run',
}
